#pragma once

#ifndef BLOGPP_BUILD_FEATURE_SERVER
#define BLOGPP_BUILD_FEATURE_SERVER 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_TAGS
#define BLOGPP_BUILD_PLUGIN_TAGS 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_ARCHIVES
#define BLOGPP_BUILD_PLUGIN_ARCHIVES 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_RSS
#define BLOGPP_BUILD_PLUGIN_RSS 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_SEARCH
#define BLOGPP_BUILD_PLUGIN_SEARCH 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_SITEMAP
#define BLOGPP_BUILD_PLUGIN_SITEMAP 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_COMMENTS
#define BLOGPP_BUILD_PLUGIN_COMMENTS 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_MATH
#define BLOGPP_BUILD_PLUGIN_MATH 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_FORUM
#define BLOGPP_BUILD_PLUGIN_FORUM 1
#endif

#ifndef BLOGPP_BUILD_PLUGIN_CLOUD
#define BLOGPP_BUILD_PLUGIN_CLOUD 1
#endif

#ifndef BLOGPP_BUILD_SERVER_PLUGIN_FORUM_API
#define BLOGPP_BUILD_SERVER_PLUGIN_FORUM_API 1
#endif
